<?php /** @var $block \Magento\Customer\Block\Account\Navigation */ ?>
<div class="block affiliate-nav">
    <div class="title">
        <strong><?php /* @escapeNotVerified */ echo __('My Affiliate'); ?></strong>
    </div>
    <div class="content">
        <nav class="affiliate-nav">
            <ul class="nav items">
                <?php echo $block->renderNavigationLink(); ?>
            </ul>
        </nav>
    </div>
</div>
